apiVersion: v1
kind: Service
metadata:
  name: website_script-service
spec:
  type: NodePort          
  selector:
    app: website_script
  ports:
  - port: 80              
    targetPort: 80       
    nodePort: 30007
